# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: PRIVACY MATTER BROWSER

on:
  release:
    types: [py]

jobs:
  deploy:

    runs-on: ubuntu-latest,window 10 

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install PyQt5==5.12.3 
            pip install PyQtWebEngine==5.12.1
            pip install PyQtWebKit
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_ tushar52}}
        TWINE_PASSWORD: ${{ secrets.PYPI_5r_qfDG3jUC8-t?}}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
